---
deployment:
  tasks:
    - /bin/cp -R /home/dataezpj/repositories/datacendia-marketing/* /home/dataezpj/public_html/
    - /bin/cp /home/dataezpj/repositories/datacendia-marketing/.htaccess /home/dataezpj/public_html/.htaccess
