/**
 * wire-pc-p2.js: Tier 2 + add-ons + Tier 3 + cross-cutting + deployment + CTA + footer
 */
const fs = require('fs');
const path = require('path');
const FILE = path.resolve(__dirname, '..', 'platform-capabilities.html');
let html = fs.readFileSync(FILE, 'utf8');
let count = 0;
function rep(o, n, k) {
  if (!html.includes(o)) { console.log('NOT FOUND: ' + k); return; }
  html = html.replace(o, n); count++;
}

rep('<span class="tier-badge tier-badge--blue">Tier 2</span>','<span class="tier-badge tier-badge--blue" data-i18n="pcTier2Badge">Tier 2</span>','pcTier2Badge');
rep('<h2 class="pc-tier-title">Enterprise</h2>','<h2 class="pc-tier-title" data-i18n="pcTier2Title">Enterprise</h2>','pcTier2Title');
rep('<p class="pc-tier-flow">Harden &rarr; Comply &rarr; Govern &rarr; Own &rarr; Scale</p>','<p class="pc-tier-flow" data-i18n="pcTier2Flow">Harden → Comply → Govern → Own → Scale</p>','pcTier2Flow');
rep('<div class="p-num">Pillar 4</div>','<div class="p-num" data-i18n="pcP4Num">Pillar 4</div>','pcP4Num');
rep('<div class="p-tag">Adversarial Testing</div>','<div class="p-tag" data-i18n="pcP4Tag">Adversarial Testing</div>','pcP4Tag');
rep('<p class="p-desc">Break your decisions before they break you.</p>','<p class="p-desc" data-i18n="pcP4Desc">Break your decisions before they break you.</p>','pcP4Desc');
rep('<li>CendiaCrucible&trade; Monte Carlo red-teaming</li>','<li data-i18n="pcP4F1">CendiaCrucible™ Monte Carlo red-teaming</li>','pcP4F1');
rep('<li>CendiaRedTeam&trade; 8-perspective attack</li>','<li data-i18n="pcP4F2">CendiaRedTeam™ 8-perspective attack</li>','pcP4F2');
rep('<li>War Games strategic simulation</li>','<li data-i18n="pcP4F3">War Games strategic simulation</li>','pcP4F3');
rep('<li>SCGE synthetic crisis injection</li>','<li data-i18n="pcP4F4">SCGE synthetic crisis injection</li>','pcP4F4');
rep('<li>Runtime security monitoring</li>','<li data-i18n="pcP4F5">Runtime security monitoring</li>','pcP4F5');
rep('<a href="wargames.html" class="p-link">War Games &rarr;</a>','<a href="wargames.html" class="p-link" data-i18n="pcP4Link">War Games →</a>','pcP4Link');
rep('<div class="p-num">Pillar 5</div>','<div class="p-num" data-i18n="pcP5Num">Pillar 5</div>','pcP5Num');
rep('<div class="p-tag">Regulatory Compliance</div>','<div class="p-tag" data-i18n="pcP5Tag">Regulatory Compliance</div>','pcP5Tag');
rep('<p class="p-desc">10 frameworks. 17 jurisdictions. Simultaneously.</p>','<p class="p-desc" data-i18n="pcP5Desc">10 frameworks. 17 jurisdictions. Simultaneously.</p>','pcP5Desc');
rep('<li>10 compliance frameworks</li>','<li data-i18n="pcP5F1">10 compliance frameworks</li>','pcP5F1');
rep('<li>17 jurisdictions simultaneously</li>','<li data-i18n="pcP5F2">17 jurisdictions simultaneously</li>','pcP5F2');
rep('<li>Regulatory Absorb&trade; (60-sec ingest)</li>','<li data-i18n="pcP5F3">Regulatory Absorb™ (60-sec ingest)</li>','pcP5F3');
rep('<li>CendiaSandbox&trade; pre-enforcement testing</li>','<li data-i18n="pcP5F4">CendiaSandbox™ pre-enforcement testing</li>','pcP5F4');
rep('<li>CendiaZKP&trade; zero-knowledge proofs</li>','<li data-i18n="pcP5F5">CendiaZKP™ zero-knowledge proofs</li>','pcP5F5');
rep('<a href="trust.html" class="p-link">Trust Center &rarr;</a>','<a href="trust.html" class="p-link" data-i18n="pcP5Link">Trust Center →</a>','pcP5Link');
rep('<div class="p-num">Pillar 6</div>','<div class="p-num" data-i18n="pcP6Num">Pillar 6</div>','pcP6Num');
rep('<div class="p-tag">Policy Enforcement</div>','<div class="p-tag" data-i18n="pcP6Tag">Policy Enforcement</div>','pcP6Tag');
rep('<p class="p-desc">Configurable guardrails, dispute resolution, and whistleblower protection.</p>','<p class="p-desc" data-i18n="pcP6Desc">Configurable guardrails, dispute resolution, and whistleblower protection.</p>','pcP6Desc');
rep('<li>CendiaGovern&trade; RBAC + approval workflows</li>','<li data-i18n="pcP6F1">CendiaGovern™ RBAC + approval workflows</li>','pcP6F1');
rep('<li>CendiaCourt&trade; AI dispute resolution</li>','<li data-i18n="pcP6F2">CendiaCourt™ AI dispute resolution</li>','pcP6F2');
rep('<li>CendiaVeto&trade; configurable blocking</li>','<li data-i18n="pcP6F3">CendiaVeto™ configurable blocking</li>','pcP6F3');
rep('<li>CendiaDissent&trade; whistleblower protection</li>','<li data-i18n="pcP6F4">CendiaDissent™ whistleblower protection</li>','pcP6F4');
rep('<li>CendiaAutopilot&trade; autonomy governance</li>','<li data-i18n="pcP6F5">CendiaAutopilot™ autonomy governance</li>','pcP6F5');
rep('<div class="p-num">Pillar 7</div>','<div class="p-num" data-i18n="pcP7Num">Pillar 7</div>','pcP7Num');
rep('<div class="p-tag">Air-Gap Architecture</div>','<div class="p-tag" data-i18n="pcP7Tag">Air-Gap Architecture</div>','pcP7Tag');
rep('<p class="p-desc">Your infrastructure. Your keys. Your data. No vendor custody.</p>','<p class="p-desc" data-i18n="pcP7Desc">Your infrastructure. Your keys. Your data. No vendor custody.</p>','pcP7Desc');
rep('<li>11 sovereign architectural patterns</li>','<li data-i18n="pcP7F1">11 sovereign architectural patterns</li>','pcP7F1');
rep('<li>Post-quantum KMS</li>','<li data-i18n="pcP7F2">Post-quantum KMS</li>','pcP7F2');
rep('<li>CendiaBlackBox&trade; sealed records</li>','<li data-i18n="pcP7F3">CendiaBlackBox™ sealed records</li>','pcP7F3');
rep('<li>CendiaMirage&trade; active deception</li>','<li data-i18n="pcP7F4">CendiaMirage™ active deception</li>','pcP7F4');
rep('<li>CAC/PIV authentication</li>','<li data-i18n="pcP7F5">CAC/PIV authentication</li>','pcP7F5');
rep('<a href="architecture.html" class="p-link">Architecture &rarr;</a>','<a href="architecture.html" class="p-link" data-i18n="pcP7Link">Architecture →</a>','pcP7Link');
rep('<div class="p-num">Pillar 8</div>','<div class="p-num" data-i18n="pcP8Num">Pillar 8</div>','pcP8Num');
rep('<div class="p-tag">CendiaOps&trade; &mdash; 19 AI Co-Pilots</div>','<div class="p-tag" data-i18n="pcP8Tag">CendiaOps™ — 19 AI Co-Pilots</div>','pcP8Tag');
rep('<p class="p-desc">AI co-pilots for every department, plus system integration and self-improvement.</p>','<p class="p-desc" data-i18n="pcP8Desc">AI co-pilots for every department, plus system integration and self-improvement.</p>','pcP8Desc');
rep('<li>19 department AI co-pilots</li>','<li data-i18n="pcP8F1">19 department AI co-pilots</li>','pcP8F1');
rep('<li>CendiaMesh&trade; system integration</li>','<li data-i18n="pcP8F2">CendiaMesh™ system integration</li>','pcP8F2');
rep('<li>CendiaPulse&trade; mission control</li>','<li data-i18n="pcP8F3">CendiaPulse™ mission control</li>','pcP8F3');
rep('<li>CendiaApotheosis&trade; nightly self-improvement</li>','<li data-i18n="pcP8F4">CendiaApotheosis™ nightly self-improvement</li>','pcP8F4');
rep('<li>100+ language translation</li>','<li data-i18n="pcP8F5">100+ language translation</li>','pcP8F5');
rep('<span class="tier-badge tier-badge--amber">Tier 2 Premium</span>','<span class="tier-badge tier-badge--amber" data-i18n="pcTier2PremiumBadge">Tier 2 Premium</span>','pcTier2PremiumBadge');
rep('<h2 class="pc-tier-title">Strategic Add-Ons</h2>','<h2 class="pc-tier-title" data-i18n="pcAddonsTitle">Strategic Add-Ons</h2>','pcAddonsTitle');
rep('<p class="pc-tier-flow">7 advanced modules for Enterprise licensees</p>','<p class="pc-tier-flow" data-i18n="pcAddonsFlow">7 advanced modules for Enterprise licensees</p>','pcAddonsFlow');
rep('<div class="addon-desc">Real-time threat intelligence</div>','<div class="addon-desc" data-i18n="pcAddon1Desc">Real-time threat intelligence</div>','pcAddon1Desc');
rep('<div class="addon-desc">100-year knowledge preservation</div>','<div class="addon-desc" data-i18n="pcAddon2Desc">100-year knowledge preservation</div>','pcAddon2Desc');
rep('<div class="addon-desc">Partnership ecosystem discovery</div>','<div class="addon-desc" data-i18n="pcAddon3Desc">Partnership ecosystem discovery</div>','pcAddon3Desc');
rep('<div class="addon-desc">Stakeholder voice assembly</div>','<div class="addon-desc" data-i18n="pcAddon4Desc">Stakeholder voice assembly</div>','pcAddon4Desc');
rep('<div class="addon-desc">Corporate narrative engine</div>','<div class="addon-desc" data-i18n="pcAddon5Desc">Corporate narrative engine</div>','pcAddon5Desc');
rep('<div class="addon-desc">Ethical drift detection</div>','<div class="addon-desc" data-i18n="pcAddon6Desc">Ethical drift detection</div>','pcAddon6Desc');
rep('<div class="addon-desc">Sustainability boundary engine</div>','<div class="addon-desc" data-i18n="pcAddon7Desc">Sustainability boundary engine</div>','pcAddon7Desc');
rep('<a href="premium.html" style="font-size:0.78rem; color:var(--color-gold); text-decoration:none;">View all Premium modules with WHO NEEDS IT qualifiers &rarr;</a>','<a href="premium.html" style="font-size:0.78rem; color:var(--color-gold); text-decoration:none;" data-i18n="pcAddonsViewAll">View all Premium modules with WHO NEEDS IT qualifiers →</a>','pcAddonsViewAll');
rep('<span class="tier-badge tier-badge--purple">Tier 3</span>','<span class="tier-badge tier-badge--purple" data-i18n="pcTier3Badge">Tier 3</span>','pcTier3Badge');
rep('<h2 class="pc-tier-title">Strategic</h2>','<h2 class="pc-tier-title" data-i18n="pcTier3Title">Strategic</h2>','pcTier3Title');
rep('<p class="pc-tier-flow">Survive &rarr; Model &rarr; Dominate &rarr; Govern Nations</p>','<p class="pc-tier-flow" data-i18n="pcTier3Flow">Survive → Model → Dominate → Govern Nations</p>','pcTier3Flow');
rep('<div class="p-num">Pillar 9</div>','<div class="p-num" data-i18n="pcP9Num">Pillar 9</div>','pcP9Num');
rep('<div class="p-tag">Institutional Failure Simulation</div>','<div class="p-tag" data-i18n="pcP9Tag">Institutional Failure Simulation</div>','pcP9Tag');
rep("<p class=\"p-desc\">18 adversarial agents simulate how institutions fail &mdash; so yours doesn&rsquo;t.</p>",'<p class="p-desc" data-i18n="pcP9Desc">18 adversarial agents simulate how institutions fail — so yours doesn\'t.</p>','pcP9Desc');
rep('<li>18 adversarial agents</li>','<li data-i18n="pcP9F1">18 adversarial agents</li>','pcP9F1');
rep('<li>7 societal failure domains</li>','<li data-i18n="pcP9F2">7 societal failure domains</li>','pcP9F2');
rep('<li>Trust Delta measurement</li>','<li data-i18n="pcP9F3">Trust Delta measurement</li>','pcP9F3');
rep('<li>Failure Envelope mapping</li>','<li data-i18n="pcP9F4">Failure Envelope mapping</li>','pcP9F4');
rep('<div class="p-num">Pillar 10</div>','<div class="p-num" data-i18n="pcP10Num">Pillar 10</div>','pcP10Num');
rep('<div class="p-tag">Societal-Scale Governance</div>','<div class="p-tag" data-i18n="pcP10Tag">Societal-Scale Governance</div>','pcP10Tag');
rep('<p class="p-desc">Model the consequences of policy at civilizational scale.</p>','<p class="p-desc" data-i18n="pcP10Desc">Model the consequences of policy at civilizational scale.</p>','pcP10Desc');
rep('<li>5 agent classes at civilizational scale</li>','<li data-i18n="pcP10F1">5 agent classes at civilizational scale</li>','pcP10F1');
rep('<li>Population-level modeling</li>','<li data-i18n="pcP10F2">Population-level modeling</li>','pcP10F2');
rep('<li>Policy impact simulation</li>','<li data-i18n="pcP10F3">Policy impact simulation</li>','pcP10F3');
rep('<li>Meta-governance oversight</li>','<li data-i18n="pcP10F4">Meta-governance oversight</li>','pcP10F4');
rep('<div class="p-num">Pillar 11</div>','<div class="p-num" data-i18n="pcP11Num">Pillar 11</div>','pcP11Num');
rep('<div class="p-tag">Industry Domination Infrastructure</div>','<div class="p-tag" data-i18n="pcP11Tag">Industry Domination Infrastructure</div>','pcP11Tag');
rep('<p class="p-desc">Deep, sector-specific governance with pre-built agents, workflows, and compliance mappings.</p>','<p class="p-desc" data-i18n="pcP11Desc">Deep, sector-specific governance with pre-built agents, workflows, and compliance mappings.</p>','pcP11Desc');
rep('<li>8 deep industry verticals</li>','<li data-i18n="pcP11F1">8 deep industry verticals</li>','pcP11F1');
rep('<li>13 sector templates</li>','<li data-i18n="pcP11F2">13 sector templates</li>','pcP11F2');
rep('<li>Legal: 14 agents, 48 modes</li>','<li data-i18n="pcP11F3">Legal: 14 agents, 48 modes</li>','pcP11F3');
rep('<li>Sports, Defense, Healthcare flagships</li>','<li data-i18n="pcP11F4">Sports, Defense, Healthcare flagships</li>','pcP11F4');
rep('<a href="verticals.html" class="p-link">View Industries &rarr;</a>','<a href="verticals.html" class="p-link" data-i18n="pcP11Link">View Industries →</a>','pcP11Link');
rep('<div class="p-num">Pillar 12</div>','<div class="p-num" data-i18n="pcP12Num">Pillar 12</div>','pcP12Num');
rep('<div class="p-tag">Nation-Scale Infrastructure</div>','<div class="p-tag" data-i18n="pcP12Tag">Nation-Scale Infrastructure</div>','pcP12Tag');
rep('<p class="p-desc">For institutions whose decisions shape economies, populations, and sovereign futures.</p>','<p class="p-desc" data-i18n="pcP12Desc">For institutions whose decisions shape economies, populations, and sovereign futures.</p>','pcP12Desc');
rep('<li>CendiaNation&trade; economic OS</li>','<li data-i18n="pcP12F1">CendiaNation™ economic OS</li>','pcP12F1');
rep('<li>CendiaOmniShield&trade; cyber defense</li>','<li data-i18n="pcP12F2">CendiaOmniShield™ cyber defense</li>','pcP12F2');
rep('<li>CendiaMarketSovereign&trade; central bank AI</li>','<li data-i18n="pcP12F3">CendiaMarketSovereign™ central bank AI</li>','pcP12F3');
rep('<li>CendiaEternum&trade; existential risk</li>','<li data-i18n="pcP12F4">CendiaEternum™ existential risk</li>','pcP12F4');
rep('<h3 class="cross-title">Cross-Cutting Platform Capabilities</h3>','<h3 class="cross-title" data-i18n="pcCrossTitle">Cross-Cutting Platform Capabilities</h3>','pcCrossTitle');
rep('<h4>Universal Data Adapters</h4>','<h4 data-i18n="pcCross1Title">Universal Data Adapters</h4>','pcCross1Title');
rep('<p>5 universal adapters connect to your existing databases. Data never leaves your infrastructure &mdash; File Watcher, Webhook, Database, Protocol, and REST connectors. No ETL. No data movement.</p>','<p data-i18n="pcCross1Desc">5 universal adapters connect to your existing databases. Data never leaves your infrastructure — File Watcher, Webhook, Database, Protocol, and REST connectors. No ETL. No data movement.</p>','pcCross1Desc');
rep('<h4>Cryptographic Evidence</h4>','<h4 data-i18n="pcCross2Title">Cryptographic Evidence</h4>','pcCross2Title');
rep('<p>Merkle tree integrity, Ed25519 signatures, RFC 3161 timestamps, post-quantum option (Dilithium, SPHINCS+).</p>','<p data-i18n="pcCross2Desc">Merkle tree integrity, Ed25519 signatures, RFC 3161 timestamps, post-quantum option (Dilithium, SPHINCS+).</p>','pcCross2Desc');
rep('<h4>CendiaOmniTranslate&trade;</h4>','<h4 data-i18n="pcCross3Title">CendiaOmniTranslate™</h4>','pcCross3Title');
rep('<p>100+ language translation with glossary management, translation memory, and RTL support. Runs entirely on your infrastructure.</p>','<p data-i18n="pcCross3Desc">100+ language translation with glossary management, translation memory, and RTL support. Runs entirely on your infrastructure.</p>','pcCross3Desc');
rep('<h4>Connector Suites</h4>','<h4 data-i18n="pcCross4Title">Connector Suites</h4>','pcCross4Title');
rep('<p>16 connector suites on 6 universal adapters. ERP, CRM, BI, EHR, databases &mdash; plug into your existing stack.</p>','<p data-i18n="pcCross4Desc">16 connector suites on 6 universal adapters. ERP, CRM, BI, EHR, databases — plug into your existing stack.</p>','pcCross4Desc');
rep('<h4>CendiaCarbonAware&trade;</h4>','<h4 data-i18n="pcCross5Title">CendiaCarbonAware™</h4>','pcCross5Title');
rep('<p>Carbon-aware workload scheduling across 10 cloud regions. Reduce AI carbon footprint by 30&ndash;50%. ESG reporting built in.</p>','<p data-i18n="pcCross5Desc">Carbon-aware workload scheduling across 10 cloud regions. Reduce AI carbon footprint by 30–50%. ESG reporting built in.</p>','pcCross5Desc');
rep('<h4>Platform AI Assistant</h4>','<h4 data-i18n="pcCross6Title">Platform AI Assistant</h4>','pcCross6Title');
rep('<p>Built-in conversational guide on every page. Context-aware suggestions, step-by-step workflows, quick action buttons.</p>','<p data-i18n="pcCross6Desc">Built-in conversational guide on every page. Context-aware suggestions, step-by-step workflows, quick action buttons.</p>','pcCross6Desc');
rep('<p style="font-size:0.7rem; color:var(--color-text-dim); text-transform:uppercase; letter-spacing:0.12em; margin-bottom:16px;">Sovereign Deployment Options</p>','<p style="font-size:0.7rem; color:var(--color-text-dim); text-transform:uppercase; letter-spacing:0.12em; margin-bottom:16px;" data-i18n="pcDeployLabel">Sovereign Deployment Options</p>','pcDeployLabel');
rep('<div class="deploy-chip">Cloud (AWS &middot; Azure &middot; GCP)</div>','<div class="deploy-chip" data-i18n="pcDeployChip1">Cloud (AWS · Azure · GCP)</div>','pcDeployChip1');
rep('<div class="deploy-chip">Private Cloud (Your VPC)</div>','<div class="deploy-chip" data-i18n="pcDeployChip2">Private Cloud (Your VPC)</div>','pcDeployChip2');
rep('<div class="deploy-chip">On-Premises (Your Data Center)</div>','<div class="deploy-chip" data-i18n="pcDeployChip3">On-Premises (Your Data Center)</div>','pcDeployChip3');
rep('<div class="deploy-chip">Air-Gapped (Isolated Networks)</div>','<div class="deploy-chip" data-i18n="pcDeployChip4">Air-Gapped (Isolated Networks)</div>','pcDeployChip4');
rep('<p style="font-size:0.72rem; color:var(--color-text-dim); max-width:600px; margin:0 auto;">All modes: your encryption keys (KMS/HSM) &middot; immutable audit ledger (your control) &middot; evidence export (standard formats) &middot; no vendor lock-in</p>','<p style="font-size:0.72rem; color:var(--color-text-dim); max-width:600px; margin:0 auto;" data-i18n="pcDeployNote">All modes: your encryption keys (KMS/HSM) · immutable audit ledger (your control) · evidence export (standard formats) · no vendor lock-in</p>','pcDeployNote');
rep('<h2>Ready to See the Full Platform?</h2>','<h2 data-i18n="pcCtaTitle">Ready to See the Full Platform?</h2>','pcCtaTitle');
rep('<p>Start with a 90-day pilot on your infrastructure. Prove value before scaling.</p>','<p data-i18n="pcCtaDesc">Start with a 90-day pilot on your infrastructure. Prove value before scaling.</p>','pcCtaDesc');
rep('<a href="briefing.html" class="pc-cta-btn">Request Briefing &rarr;</a>','<a href="briefing.html" class="pc-cta-btn" data-i18n="pcCtaBtn">Request Briefing →</a>','pcCtaBtn');
rep('<a href="pilot.html" class="pc-cta-link">Or start with a pilot &rarr;</a>','<a href="pilot.html" class="pc-cta-link" data-i18n="pcCtaLink">Or start with a pilot →</a>','pcCtaLink');
rep('<p class="footer-outcome">Ready to own your AI decisions&mdash;and prove them to regulators?</p>','<p class="footer-outcome" data-i18n="footerOutcome">Ready to own your AI decisions—and prove them to regulators?</p>','footerOutcome');
rep('<a href="pilot.html" class="cta-button secondary">See Results in 90 Days</a>','<a href="pilot.html" class="cta-button secondary" data-i18n="footerSeeResults">See Results in 90 Days</a>','footerSeeResults');

fs.writeFileSync(FILE, html, 'utf8');
console.log('PC Part 2 done — ' + count + ' replacements.');
console.log('data-i18n count: ' + (html.match(/data-i18n/g)||[]).length);
